### ISSUE TITLE
Phone (Android) Companion App (Preliminary)

### ISSUE THREAD

**Issue by kaysoky** [kaysoky/PREvent#3]
- Phone must support Bluetooth 4.0
- Phone must have GPS and data connection
- TODO: Scope out more requirements

**Comment by kaysoky** [comment]
@amberMZ Note that this has been changed to Android.  Change your plans accordingly, but at least there aren't any paywalls.

**Comment by kaysoky** [comment]
Check out this for [Bluetooth Documentation](https://www.bluegiga.com/en-US/products/ble112-bluetooth-smart-module/#documentation)

**Comment by amberMZ** [comment]
Yep I'll just start learning Android Studio and thanks a lot for the bluetooth documentations!
